image: ubuntu:latest

variables:
  IMAGE_NAME: registry.example.com/reactjs/react-simple-boilerplate:$CI_COMMIT_REF_NAME

stages:
  - build

build:
  stage: build
  script:
    - docker login -u $RUNNER_REGISTRY_USER -p $RUNNER_REGISTRY_PASSWORD registry.example.com
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
