image: node:latest
image: docker:latest

cache:
  paths:
    - node_modules/

stages:
  - test
  - build

testing:
  stage: test
  script:
    - npm install
    - npm run test:ci
    - npm run coverage
  only:
    - develop
    - master
  tags:
    - docker

develop:
  stage: build
  only:
    - develop
  script:
    - npm run build
    - docker login -u $CI_REGISTRY_PASSWORD -p $CI_REGISTRY_USER $CI_REGISTRY
    - docker build --no-cache -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  tags:
    - docker
