image: docker:stable

variables:
  REGISTRY_PATH: "registry.example.com/root/react-simple-boilerplate"

development_test:
  stage: dev
  script:
    - echo $REGISTRY_PATH:$CI_JOB_STAGE-$CI_COMMIT_SHORT_SHA
  tags:
    - docker
# development_build:
#   stage: build
#   valiables:
#     - IMAGE_NAME: "$REGISTRY_PATH:$CI_JOB_STAGE-$CI_COMMIT_SHORT_SHA"
#   only:
#     refs:
#       - development
#   script:
#     - docker login -u $RUNNER_REGISTRY_USER -p $RUNNER_REGISTRY_PASSWORD registry.example.com
#     - docker build -t $IMAGE_NAME .
#     - docker push $IMAGE_NAME
#   tags:
#     - docker
